create or replace PACKAGE PKG_SCD2 AUTHID CURRENT_USER AS 

  -- load_data --
  procedure load_data(
    p_src_table varchar2, 
    p_int_table varchar2, 
    p_trg_table varchar2,
    p_pk_column varchar2,
    p_key_columns varchar2,
    p_compare_columns clob,
    p_other_columns varchar2,
    p_verbose varchar2:='Y',
    p_execute varchar2:='N'
  );
  
  -- primary key
  function fn_get_pk(p_table_name varchar2) return varchar2;
  -- business key
  function fn_get_biz_key(p_table_name varchar2) return varchar2;
  -- cols to compare
  function fn_get_comp_flds(p_table_name varchar2) return clob;
  -- cols to ignore
  function fn_get_othr_flds(p_table_name varchar2) return varchar2;
  
  -- create_scd2_tables
  procedure create_scd2_tables(p_table_name varchar2, p_trg_schema varchar2);
  
  ----------------
  -- LOG_START --
  ----------------
  -- l_log_evt_id := LOG_START ( p_evt_name => 'p_evt_name', p_table_name =>  'p_table_name', p_info =>  'p_info', p_clob =>  'null' );
  FUNCTION LOG_START (
    p_evt_name in varchar2,
    p_parent_id in int:=null,
    p_table_name in varchar2:=null,
    p_info in varchar2:=null,
    p_clob in clob:= null
  ) return number;
  
  -- LOG_END --
  -- LOG_END ( p_evt_id => l_log_evt_id, p_row_count => SQL%rowcount, p_info =>  'p_info');
  PROCEDURE LOG_END (p_evt_id in int, p_row_count int:=null, p_info in varchar2:=null);
  
  -- LOG_ERROR --
  -- LOG_ERROR ( p_evt_id => l_log_evt_id);
  PROCEDURE LOG_ERROR (p_evt_id in int);

/* 
-- DDL ovi tablica:

-- SCD2_CLOB_LOG --
CREATE TABLE SCD2_CLOB_LOG (
  "ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EVT_NAME" VARCHAR2(128 CHAR), 
	"LOG_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp, 
	"LOG_CLOB" CLOB
);
  
  -- SCD2_EVT_LOG --
CREATE TABLE SCD2_EVT_LOG (
  "ID" NUMBER(*,0),
  parent_id int,
	"EVT_NAME" VARCHAR2(255 CHAR), 
	"USER_CREATED" VARCHAR2(255 CHAR) DEFAULT user, 
	"DATETIME_START" TIMESTAMP (6) DEFAULT systimestamp, 
	"DATETIME_END" TIMESTAMP (6), 
	"DURATION_SEC" NUMBER(20,6), 
	"TABLE_NAME" VARCHAR2(255 CHAR), 
	"ROW_COUNT" NUMBER(38,0), 
	"STATUS" VARCHAR2(10 CHAR), 
	"ERROR_MESSAGE" VARCHAR2(2000 CHAR), 
	"INFO_MESSAGE" VARCHAR2(500 CHAR), 
	"CLOB_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
);

-- SEQ_SCD2_EVT_LOG --
CREATE SEQUENCE  SEQ_SCD2_EVT_LOG  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 
NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

-- SEQ_SCD2_BATCH_ID --
CREATE SEQUENCE  SEQ_SCD2_BATCH_ID
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 
NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
*/

END PKG_SCD2;
